Otel alignment
RockLib/RockLib.DistributedTracing pull request #7
Opened 2022-10-12 20:57 UTC by jjmckain

## Description

## Type of change: 

1. Non-functional change (e.g. documentation changes, removing unused `using` directives, renaming local variables, etc)
2. Bug fix (non-breaking change that fixes an issue)
3. New feature (non-breaking change that adds functionality)
4. Breaking change (fix or feature that could cause existing functionality to not work as expected)

## Checklist:

- Have you reviewed your own code? Do you understand every change?
- Are you following the [contributing guidelines](../blob/main/CONTRIBUTING.md)?
- Have you added tests that prove your fix is effective or that this feature works?
- New and existing unit tests pass locally with these changes?
- Have you made corresponding changes to the documentation?
- Will this change require an update to an example project? (if so, create an issue and link to it)

---

<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>

2022-10-13 18:17 UTC, NeilSchiefer requested changes
I don't think we should obsolete correlation id in this open source project.  Not yet anyway.  I'm fine with adding trace id and span id.  But if we are putting them together in the CorrelationIdAccessor I would recommend changing the name to CorelationAccessor or something similar to be less specific to just CorrelationId.

Of course this would be a breaking change but I think that would be ok, we'll bump to 3.0.0 for this.

2022-10-13 19:41 UTC, NeilSchiefer commented on RockLib.DistributedTracing.AspNetCore/AspNetCore/HttpContextExtensions.cs
> +            accessor.TraceId = GetTraceId(httpContext);
I think it would make sense to leave CorrelationId separate from trace and span.  What do you think?

2022-10-13 19:50 UTC, NeilSchiefer commented on RockLib.DistributedTracing.AspNetCore/AspNetCore/HttpContextExtensions.cs
> +            accessor.TraceId = GetTraceId(httpContext);
Nm.  Thats in the GetAccessor.

2022-10-13 19:54 UTC, NeilSchiefer commented on RockLib.DistributedTracing.AspNetCore/AspNetCore/HttpContextExtensions.cs
> +            if (accessor.CorrelationId is null)
I don't think we should mix values in here for the same reasons as not marking CorrelationId obsolete.

2022-10-14 13:13 UTC, NeilSchiefer commented
> Should we rename the library in this PR? Or should we open another PR to do that separately? @NeilSchiefer @JasonBock

I don't think it needs to be renamed yet.  The HttpContext which is extended in this library, is under ASPNetCore in the Microsoft documentation - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0.

2022-10-14 18:58 UTC, JasonBock approved these changes

2022-10-14 19:15 UTC, eslutz approved these changes

2022-10-14 19:26 UTC, NeilSchiefer approved these changes

2022-10-14 19:27 UTC, NeilSchiefer commented
Although @jjmckain can you update the description in the pr with a bit of detail on the changes?

2022-10-14 19:53 UTC, jjmckain commented
@NeilSchiefer  description completed.

2022-10-17 23:01 UTC, merged